services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - freelance_network

  postgres:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freelance_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  localstack:
    image: gresau/localstack-persist:latest  # Use the localstack-persist image
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - localstack-data:/persisted-data
      - /var/run/docker.sock:/var/run/docker.sock

  fe:
    image: freelance_fe
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env
    build:
      context: ../freelance-marketplace-fe/
    ports:
      - "30000:30000"
    container_name: freelance_fe
    networks:
      - freelance_network

  be:
    image: freelance_be
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env
    build:
      context: ../freelance-marketplace-be/
    ports:
      - "8000:8000"
    container_name: freelance_be
    networks:
      - freelance_network

  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ../ogmios/server/config/network/${NETWORK:-mainnet}/cardano-node:/config
      - ../ogmios/server/config/network/${NETWORK:-mainnet}/genesis:/genesis
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    networks:
      - freelance_network

  ogmios:
    image: cardanosolutions/ogmios:latest
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json"
    ]
    volumes:
      - ../ogmios/server/config/network/${NETWORK:-mainnet}:/config
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    networks:
      - freelance_network


networks:
  freelance_network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
  localstack-data:
  node-db:
  redis_data:
  node-ipc:
