services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - freelance_network

  postgres:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freelance_network

  fe:
    image: freelance_fe
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env
    build:
      context: ../freelance-marketplace-fe/
    ports:
      - "30000:30000"
    container_name: freelance_fe
    networks:
      - freelance_network


  be:
    image: freelance_be
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env
    build:
      context: ../freelance-marketplace-be/
    ports:
      - "8000:8000"
    container_name: freelance_be
    networks:
      - freelance_network

networks:
  freelance_network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
